  market_maker_mariadb:
    image: mariadb:10.1
    container_name: market_maker_mariadb
    ports:
     - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=market_maker
      - VIRTUAL_HOST=mariadb.market_maker.net
    volumes:
     - "/datadrive/mariadb_market_maker:/var/lib/mysql"
  market_maker_cubes:
    build: ./cube_server
    container_name: market_maker_cubes
    ports:
     - "5000:5000"
    environment:
      - VIRTUAL_HOST=cube.market_maker.net
      - VIRTUAL_PORT=5000
      - JUPYTER_ENDPOINT=false
      - CONNECTION_STRING=mysql+pymysql://root:market_maker@market_maker_mariadb/market_maker
      - STARTUP_BEHAVIOR=clean-import
    links:
      - market_maker_mariadb  
  nginx_market_maker:
    image: jwilder/nginx-proxy
    container_name: nginx_market_maker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /mnt/resource/log/nginx:/var/log/nginx/
